name: "Build and deploy"

on: [push,  workflow_dispatch]

env: 
  NETCORE_VERSION: '3.1'  # set correct version here
  PACKAGE_PATH: './published'

jobs:
  build:
    name: Build and deploy job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: Restore with dotnet
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore -c Release 

    - name: Create artifacts
      run: dotnet publish --no-build -c Release -o ${{ env.PACKAGE_PATH }}
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: resharper
        uses: glassechidna/resharper-action@master
        with:
          solution: SimpleWebApi.sln
      - name: resharper report 
        uses: glassechidna/resharper-action@master
        with:
          solution: /tmp/report.xml