name: "Build and deploy"

on: [push,  workflow_dispatch]

env: 
  NETCORE_VERSION: '3.1'  # set correct version here
  PACKAGE_PATH: './published'
  RESHARPER_CLI_NAME: 'JetBrains.ReSharper.CommandLineTools.Unix'
  RESHARPER_CLI_VERSION: "2019.2.3"

jobs:
  build:
    name: Build and deploy job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
    - name: Restore with dotnet
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --no-restore -c Release 

    - name: Create artifacts
      run: dotnet publish --no-build -c Release -o ${{ env.PACKAGE_PATH }}
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Resharper Code Quality
        run: |
            # apt update && apt install -y curl zip unzip
            curl -LO "https://download.jetbrains.com/resharper/ReSharperUltimate.$RESHARPER_CLI_VERSION/$RESHARPER_CLI_NAME.$RESHARPER_CLI_VERSION.zip"
            unzip -q $RESHARPER_CLI_NAME.$RESHARPER_CLI_VERSION.zip -d "resharper"
            mkdir -p CodeQuality
            files=(*.sln)
            sh ./resharper/dupfinder.sh "${files[0]}" --output=CodeQuality/dupfinderReport.html --format=Html
            sh ./resharper/inspectcode.sh "${files[0]}" --output=CodeQuality/results.xml
      - uses: actions/upload-artifact@v1
        with:
          name: CodeQuality
          path: CodeQuality
      - name: resharper report 
        uses: glassechidna/resharper-action@master
        with:
          solution: CodeQuality/results.xml